hydra:
  run:
    dir: ./outputs/${hydra.job.config_name}-${data.name}-${model.encoder}-${model.pooling}

  sweep:
    dir: ./outputs/
    subdir: ${hydra.job.config_name}-${data.name}-${model.encoder}-${model.pooling}
