hydra:
  run:
    dir: ./outputs/${data.name}-${model.encoder}-${model.pooling}-${model.normalizer}

  sweep:
    dir: ./outputs/
    subdir: ${data.name}-${model.encoder}-${model.pooling}-${model.normalizer}
