graph:
    name: aviation
    path: 'data/graph/aviation/graph.json'
    embedding: 'data/graph/aviation/embedding.json'
    raw_path: 'data/graph/aviation/preprocessing.json'
    num_categories: 11
    categories:
        - 'Airport [A]'
        - 'Airline [B]'
        - 'Aircraft [C]'
        - 'Components [D]'
        - 'Engine [E]'
        - 'Fault [F]'
        - 'Geographic Location [G]'
        - 'Manufacturer [H]'
        - 'Material [I]'
        - 'Person [J]'
        - 'Unit [L]'
