graph:
    name: aviation
    path: 'data/aviation/graph/graph.json'
    embedding: 'data/aviation/node2vec/graph.json'
    num_categories: 12
    categories:
        - 'Airport [A]'
        - 'Airline [B]'
        - 'Aircraft [C]'
        - 'Components [D]'
        - 'Engine [E]'
        - 'Fault [F]'
        - 'Geographic Location [G]'
        - 'Manufacturer [H]'
        - 'Material [I]'
        - 'Person [J]'
        - 'Process [K]'
        - 'Unit [L]'
