data:
  name: aviation_email_classification
  base_path: 'data/classification/aviation/email/train.txt'
  train_path: 'data/classification/aviation/email/train.txt'
  test_path: False
  should_stop: True
  should_sample: False
  samples: 0
  max_length: 300
  split: 0.3
  shuffle_before_split: True
  random_state: 42
