data:
  name: biosses
  raw_path: 'data/experiment/sentence_similarity/biosses/biosses.csv'
  train_path: 'data/experiment/sentence_similarity/biosses/train.txt'
  test_path: 'data/experiment/sentence_similarity/biosses/test.txt'
  should_stop: True
  should_sample: False
  max_length: 40
  split: 0.1
  shuffle_before_split: False
  random_state: 42
