data:
  name: ohsumed_classification
  raw_path: 'data/experiment/classification/hallmarks/oversampled'
  train_path: 'data/experiment/classification/hallmarks/train.txt'
  test_path: 'data/experiment/classification/hallmarks/test.txt'
  should_stop: True
  should_sample: False
  samples: 0
  max_length: 500
  split: 0.3
  shuffle_before_split: True
  random_state: 42
