data:
  name: ohsumed_ablation
  base_path: 'data/ohsumed.txt'
  train_path: 'data/benchmark/ohsumed_ablation.txt'
  test_path: False
  should_stop: True
  should_sample: False
  max_length: 286
  split: 0.3
  shuffle_before_split: True
  random_state: 42
  samples_per_category: 100
