data:
  name: ohsumed_classification
  raw_train_path: 'data/experiment/classification/ohsumed/train/'
  raw_test_path: 'data/experiment/classification/ohsumed/test/'
  train_path: 'data/experiment/classification/ohsumed/train.txt'
  test_path: 'data/experiment/classification/ohsumed/test.txt'
  should_stop: True
  should_sample: False
  samples: 0
  max_length: 400
  split: 0.3
  shuffle_before_split: True
  random_state: 42
